# Generated by Django 3.1 on 2020-08-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagenotification',
            old_name='n_counter',
            new_name='ncounter',
        ),
    ]
