# Generated by Django 3.1 on 2020-08-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_auto_20200819_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagenotification',
            name='type',
            field=models.CharField(default='message', max_length=30),
        ),
    ]
