# Generated by Django 3.1 on 2020-08-19 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cover_Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverImage', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'cover_Pic',
            },
        ),
        migrations.CreateModel(
            name='profile_Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'profile_Pic',
            },
        ),
        migrations.CreateModel(
            name='user_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, max_length=15, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('lives_in', models.CharField(blank=True, max_length=80, null=True)),
                ('hometown', models.CharField(blank=True, max_length=80, null=True)),
                ('relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('work_at', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'user_Detail',
            },
        ),
    ]
