# Generated by Django 3.0.5 on 2020-08-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0003_auto_20200820_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlikenotifications',
            name='n_o_c',
            field=models.TextField(default=1),
        ),
    ]
