# Generated by Django 3.0.5 on 2020-08-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0004_auto_20200821_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlikenotifications',
            name='n_o_c',
            field=models.IntegerField(),
        ),
    ]
