# Generated by Django 3.0.5 on 2020-08-26 22:59

from django.db import migrations, models
import user_accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0006_delete_commentlikenotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page',
            field=models.CharField(blank=True, default=user_accounts.models.User, max_length=20, null=True),
        ),
    ]
