# Generated by Django 3.0.5 on 2020-08-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0007_post_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='page',
            field=models.CharField(blank=True, default='me', max_length=20, null=True),
        ),
    ]
