# Generated by Django 3.0.5 on 2020-08-27 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0010_auto_20200827_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
