# Generated by Django 3.0.5 on 2020-08-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_birthdaynotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='birthdayNotification',
        ),
    ]
